server:
  port: 80

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:7001/eureka/


#ribbon配置1
#ribbon:
#  OkToRetryOnAllOperations: false #对所有操作请求都进行重试,默认false
#  ReadTimeout: 5000   #负载均衡超时时间，默认值5000
#  ConnectTimeout: 3000 #ribbon请求连接的超时时间，默认值2000
#  MaxAutoRetries: 0     #对当前实例的重试次数，默认0
#  MaxAutoRetriesNextServer: 1 #对切换实例的重试次数，默认1

#ribbon配置2
ribbon:
  #  指的是建立连接后从服务器读取到可用资源所用的时间
  ReadTimeout: 5000
  #  指的是建立连接所用的时间 , 适用于网络状态正常的情况下 , 两端连接所用的时间
  ConnectTimeout: 5000

#用于服务降级 在注解@FeignClient中添加fallbackFactory属性值
feign:
  hystrix:
    enabled: true
